project_name: redfish_exporter
version: 2
builds:
  - id: default
    binary: redfish_exporter
    main: ./cmd/redfish_exporter
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
dockers:
  - id: ghcr.io
    image_templates:
      - "ghcr.io/freekingdean/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/freekingdean/{{ .ProjectName }}:{{ .Major }}"
      - "ghcr.io/freekingdean/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/freekingdean/{{ .ProjectName }}:latest"
