name: semantic-release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
    packages: write # to be able to push container images
    contents: write # to be able to publish a GitHub release

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sed Tag
        run: |
          sed -i "s/<<TAG>>/${{ github.ref_name }}/g" ./charts/redfish-exporter/Chart.yaml

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Chartreleaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          install_only: true

      - name: Run Chartreleaser
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          cr package charts/redfish-exporter
          cr upload -o freekingdean -r redfish_exporter --make-release-latest=false
          cr index -o freekingdean -r redfish_exporter

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
